// source: v2/profile/profile.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var v2_core_msg_options_core_options_pb = require('../../v2/core_msg_options/core_options_pb.js');
goog.object.extend(proto, v2_core_msg_options_core_options_pb);
goog.exportSymbol('proto.profile.ProfileEntity', null, global);
goog.exportSymbol('proto.profile.ProfileOptions', null, global);
goog.exportSymbol('proto.profile.SubscriptionInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.profile.ProfileEntity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.profile.ProfileEntity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.profile.ProfileEntity.displayName = 'proto.profile.ProfileEntity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.profile.ProfileOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.profile.ProfileOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.profile.ProfileOptions.displayName = 'proto.profile.ProfileOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.profile.SubscriptionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.profile.SubscriptionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.profile.SubscriptionInfo.displayName = 'proto.profile.SubscriptionInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.profile.ProfileEntity.prototype.toObject = function(opt_includeInstance) {
  return proto.profile.ProfileEntity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.profile.ProfileEntity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.ProfileEntity.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    url: jspb.Message.getFieldWithDefault(msg, 4, ""),
    lastUpdate: jspb.Message.getFieldWithDefault(msg, 5, 0),
    options: (f = msg.getOptions()) && proto.profile.ProfileOptions.toObject(includeInstance, f),
    subInfo: (f = msg.getSubInfo()) && proto.profile.SubscriptionInfo.toObject(includeInstance, f),
    overrideCoreOptions: (f = msg.getOverrideCoreOptions()) && v2_core_msg_options_core_options_pb.CoreOptions.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.profile.ProfileEntity}
 */
proto.profile.ProfileEntity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.profile.ProfileEntity;
  return proto.profile.ProfileEntity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.profile.ProfileEntity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.profile.ProfileEntity}
 */
proto.profile.ProfileEntity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastUpdate(value);
      break;
    case 6:
      var value = new proto.profile.ProfileOptions;
      reader.readMessage(value,proto.profile.ProfileOptions.deserializeBinaryFromReader);
      msg.setOptions(value);
      break;
    case 7:
      var value = new proto.profile.SubscriptionInfo;
      reader.readMessage(value,proto.profile.SubscriptionInfo.deserializeBinaryFromReader);
      msg.setSubInfo(value);
      break;
    case 8:
      var value = new v2_core_msg_options_core_options_pb.CoreOptions;
      reader.readMessage(value,v2_core_msg_options_core_options_pb.CoreOptions.deserializeBinaryFromReader);
      msg.setOverrideCoreOptions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.profile.ProfileEntity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.profile.ProfileEntity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.profile.ProfileEntity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.ProfileEntity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLastUpdate();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getOptions();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.profile.ProfileOptions.serializeBinaryToWriter
    );
  }
  f = message.getSubInfo();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.profile.SubscriptionInfo.serializeBinaryToWriter
    );
  }
  f = message.getOverrideCoreOptions();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      v2_core_msg_options_core_options_pb.CoreOptions.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.profile.ProfileEntity.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.profile.ProfileEntity} returns this
 */
proto.profile.ProfileEntity.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.profile.ProfileEntity.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.profile.ProfileEntity} returns this
 */
proto.profile.ProfileEntity.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string url = 4;
 * @return {string}
 */
proto.profile.ProfileEntity.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.profile.ProfileEntity} returns this
 */
proto.profile.ProfileEntity.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 last_update = 5;
 * @return {number}
 */
proto.profile.ProfileEntity.prototype.getLastUpdate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.profile.ProfileEntity} returns this
 */
proto.profile.ProfileEntity.prototype.setLastUpdate = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional ProfileOptions options = 6;
 * @return {?proto.profile.ProfileOptions}
 */
proto.profile.ProfileEntity.prototype.getOptions = function() {
  return /** @type{?proto.profile.ProfileOptions} */ (
    jspb.Message.getWrapperField(this, proto.profile.ProfileOptions, 6));
};


/**
 * @param {?proto.profile.ProfileOptions|undefined} value
 * @return {!proto.profile.ProfileEntity} returns this
*/
proto.profile.ProfileEntity.prototype.setOptions = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.profile.ProfileEntity} returns this
 */
proto.profile.ProfileEntity.prototype.clearOptions = function() {
  return this.setOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.profile.ProfileEntity.prototype.hasOptions = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional SubscriptionInfo sub_info = 7;
 * @return {?proto.profile.SubscriptionInfo}
 */
proto.profile.ProfileEntity.prototype.getSubInfo = function() {
  return /** @type{?proto.profile.SubscriptionInfo} */ (
    jspb.Message.getWrapperField(this, proto.profile.SubscriptionInfo, 7));
};


/**
 * @param {?proto.profile.SubscriptionInfo|undefined} value
 * @return {!proto.profile.ProfileEntity} returns this
*/
proto.profile.ProfileEntity.prototype.setSubInfo = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.profile.ProfileEntity} returns this
 */
proto.profile.ProfileEntity.prototype.clearSubInfo = function() {
  return this.setSubInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.profile.ProfileEntity.prototype.hasSubInfo = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional core_msg_options.CoreOptions override_core_options = 8;
 * @return {?proto.core_msg_options.CoreOptions}
 */
proto.profile.ProfileEntity.prototype.getOverrideCoreOptions = function() {
  return /** @type{?proto.core_msg_options.CoreOptions} */ (
    jspb.Message.getWrapperField(this, v2_core_msg_options_core_options_pb.CoreOptions, 8));
};


/**
 * @param {?proto.core_msg_options.CoreOptions|undefined} value
 * @return {!proto.profile.ProfileEntity} returns this
*/
proto.profile.ProfileEntity.prototype.setOverrideCoreOptions = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.profile.ProfileEntity} returns this
 */
proto.profile.ProfileEntity.prototype.clearOverrideCoreOptions = function() {
  return this.setOverrideCoreOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.profile.ProfileEntity.prototype.hasOverrideCoreOptions = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.profile.ProfileOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.profile.ProfileOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.profile.ProfileOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.ProfileOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    updateInterval: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.profile.ProfileOptions}
 */
proto.profile.ProfileOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.profile.ProfileOptions;
  return proto.profile.ProfileOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.profile.ProfileOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.profile.ProfileOptions}
 */
proto.profile.ProfileOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdateInterval(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.profile.ProfileOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.profile.ProfileOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.profile.ProfileOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.ProfileOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdateInterval();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 update_interval = 1;
 * @return {number}
 */
proto.profile.ProfileOptions.prototype.getUpdateInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.profile.ProfileOptions} returns this
 */
proto.profile.ProfileOptions.prototype.setUpdateInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.profile.SubscriptionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.profile.SubscriptionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.profile.SubscriptionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.SubscriptionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    upload: jspb.Message.getFieldWithDefault(msg, 1, 0),
    download: jspb.Message.getFieldWithDefault(msg, 2, 0),
    total: jspb.Message.getFieldWithDefault(msg, 3, 0),
    expire: jspb.Message.getFieldWithDefault(msg, 4, 0),
    webPageUrl: jspb.Message.getFieldWithDefault(msg, 5, ""),
    supportUrl: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.profile.SubscriptionInfo}
 */
proto.profile.SubscriptionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.profile.SubscriptionInfo;
  return proto.profile.SubscriptionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.profile.SubscriptionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.profile.SubscriptionInfo}
 */
proto.profile.SubscriptionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpload(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDownload(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTotal(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpire(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setWebPageUrl(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSupportUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.profile.SubscriptionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.profile.SubscriptionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.profile.SubscriptionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.SubscriptionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpload();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getDownload();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getExpire();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getWebPageUrl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSupportUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional int64 upload = 1;
 * @return {number}
 */
proto.profile.SubscriptionInfo.prototype.getUpload = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.profile.SubscriptionInfo} returns this
 */
proto.profile.SubscriptionInfo.prototype.setUpload = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 download = 2;
 * @return {number}
 */
proto.profile.SubscriptionInfo.prototype.getDownload = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.profile.SubscriptionInfo} returns this
 */
proto.profile.SubscriptionInfo.prototype.setDownload = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 total = 3;
 * @return {number}
 */
proto.profile.SubscriptionInfo.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.profile.SubscriptionInfo} returns this
 */
proto.profile.SubscriptionInfo.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 expire = 4;
 * @return {number}
 */
proto.profile.SubscriptionInfo.prototype.getExpire = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.profile.SubscriptionInfo} returns this
 */
proto.profile.SubscriptionInfo.prototype.setExpire = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string web_page_url = 5;
 * @return {string}
 */
proto.profile.SubscriptionInfo.prototype.getWebPageUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.profile.SubscriptionInfo} returns this
 */
proto.profile.SubscriptionInfo.prototype.setWebPageUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string support_url = 6;
 * @return {string}
 */
proto.profile.SubscriptionInfo.prototype.getSupportUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.profile.SubscriptionInfo} returns this
 */
proto.profile.SubscriptionInfo.prototype.setSupportUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.profile);
