// source: v2/config/route_rule.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.config.Network', null, global);
goog.exportSymbol('proto.config.Outbound', null, global);
goog.exportSymbol('proto.config.Protocol', null, global);
goog.exportSymbol('proto.config.RouteRule', null, global);
goog.exportSymbol('proto.config.Rule', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.config.RouteRule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.config.RouteRule.repeatedFields_, null);
};
goog.inherits(proto.config.RouteRule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.config.RouteRule.displayName = 'proto.config.RouteRule';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.config.Rule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.config.Rule.repeatedFields_, null);
};
goog.inherits(proto.config.Rule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.config.Rule.displayName = 'proto.config.Rule';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.config.RouteRule.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.config.RouteRule.prototype.toObject = function(opt_includeInstance) {
  return proto.config.RouteRule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.config.RouteRule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.config.RouteRule.toObject = function(includeInstance, msg) {
  var f, obj = {
    rulesList: jspb.Message.toObjectList(msg.getRulesList(),
    proto.config.Rule.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.config.RouteRule}
 */
proto.config.RouteRule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.config.RouteRule;
  return proto.config.RouteRule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.config.RouteRule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.config.RouteRule}
 */
proto.config.RouteRule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.config.Rule;
      reader.readMessage(value,proto.config.Rule.deserializeBinaryFromReader);
      msg.addRules(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.config.RouteRule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.config.RouteRule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.config.RouteRule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.config.RouteRule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRulesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.config.Rule.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Rule rules = 1;
 * @return {!Array<!proto.config.Rule>}
 */
proto.config.RouteRule.prototype.getRulesList = function() {
  return /** @type{!Array<!proto.config.Rule>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.config.Rule, 1));
};


/**
 * @param {!Array<!proto.config.Rule>} value
 * @return {!proto.config.RouteRule} returns this
*/
proto.config.RouteRule.prototype.setRulesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.config.Rule=} opt_value
 * @param {number=} opt_index
 * @return {!proto.config.Rule}
 */
proto.config.RouteRule.prototype.addRules = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.config.Rule, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.RouteRule} returns this
 */
proto.config.RouteRule.prototype.clearRulesList = function() {
  return this.setRulesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.config.Rule.repeatedFields_ = [5,6,7,8,10,11,12,13,14,15,16,17,18];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.config.Rule.prototype.toObject = function(opt_includeInstance) {
  return proto.config.Rule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.config.Rule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.config.Rule.toObject = function(includeInstance, msg) {
  var f, obj = {
    listOrder: jspb.Message.getFieldWithDefault(msg, 1, 0),
    enabled: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    outbound: jspb.Message.getFieldWithDefault(msg, 4, 0),
    ruleSetsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    packageNamesList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    processNamesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    processPathsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    network: jspb.Message.getFieldWithDefault(msg, 9, 0),
    portRangesList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    sourcePortRangesList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    protocolsList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    ipCidrsList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    sourceIpCidrsList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    domainsList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    domainSuffixesList: (f = jspb.Message.getRepeatedField(msg, 16)) == null ? undefined : f,
    domainKeywordsList: (f = jspb.Message.getRepeatedField(msg, 17)) == null ? undefined : f,
    domainRegexesList: (f = jspb.Message.getRepeatedField(msg, 18)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.config.Rule}
 */
proto.config.Rule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.config.Rule;
  return proto.config.Rule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.config.Rule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.config.Rule}
 */
proto.config.Rule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setListOrder(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {!proto.config.Outbound} */ (reader.readEnum());
      msg.setOutbound(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addRuleSets(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addPackageNames(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addProcessNames(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addProcessPaths(value);
      break;
    case 9:
      var value = /** @type {!proto.config.Network} */ (reader.readEnum());
      msg.setNetwork(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addPortRanges(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addSourcePortRanges(value);
      break;
    case 12:
      var values = /** @type {!Array<!proto.config.Protocol>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addProtocols(values[i]);
      }
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addIpCidrs(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addSourceIpCidrs(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addDomains(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.addDomainSuffixes(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.addDomainKeywords(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.addDomainRegexes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.config.Rule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.config.Rule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.config.Rule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.config.Rule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getListOrder();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOutbound();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getRuleSetsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getPackageNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getProcessNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getProcessPathsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getNetwork();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getPortRangesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getSourcePortRangesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getProtocolsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      12,
      f
    );
  }
  f = message.getIpCidrsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getSourceIpCidrsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getDomainsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getDomainSuffixesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      16,
      f
    );
  }
  f = message.getDomainKeywordsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      17,
      f
    );
  }
  f = message.getDomainRegexesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      18,
      f
    );
  }
};


/**
 * optional uint32 list_order = 1;
 * @return {number}
 */
proto.config.Rule.prototype.getListOrder = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setListOrder = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool enabled = 2;
 * @return {boolean}
 */
proto.config.Rule.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.config.Rule.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Outbound outbound = 4;
 * @return {!proto.config.Outbound}
 */
proto.config.Rule.prototype.getOutbound = function() {
  return /** @type {!proto.config.Outbound} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.config.Outbound} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setOutbound = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * repeated string rule_sets = 5;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getRuleSetsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setRuleSetsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addRuleSets = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearRuleSetsList = function() {
  return this.setRuleSetsList([]);
};


/**
 * repeated string package_names = 6;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getPackageNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setPackageNamesList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addPackageNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearPackageNamesList = function() {
  return this.setPackageNamesList([]);
};


/**
 * repeated string process_names = 7;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getProcessNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setProcessNamesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addProcessNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearProcessNamesList = function() {
  return this.setProcessNamesList([]);
};


/**
 * repeated string process_paths = 8;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getProcessPathsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setProcessPathsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addProcessPaths = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearProcessPathsList = function() {
  return this.setProcessPathsList([]);
};


/**
 * optional Network network = 9;
 * @return {!proto.config.Network}
 */
proto.config.Rule.prototype.getNetwork = function() {
  return /** @type {!proto.config.Network} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.config.Network} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setNetwork = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * repeated string port_ranges = 10;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getPortRangesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setPortRangesList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addPortRanges = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearPortRangesList = function() {
  return this.setPortRangesList([]);
};


/**
 * repeated string source_port_ranges = 11;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getSourcePortRangesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setSourcePortRangesList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addSourcePortRanges = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearSourcePortRangesList = function() {
  return this.setSourcePortRangesList([]);
};


/**
 * repeated Protocol protocols = 12;
 * @return {!Array<!proto.config.Protocol>}
 */
proto.config.Rule.prototype.getProtocolsList = function() {
  return /** @type {!Array<!proto.config.Protocol>} */ (jspb.Message.getRepeatedField(this, 12));
};


/**
 * @param {!Array<!proto.config.Protocol>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setProtocolsList = function(value) {
  return jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {!proto.config.Protocol} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addProtocols = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearProtocolsList = function() {
  return this.setProtocolsList([]);
};


/**
 * repeated string ip_cidrs = 13;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getIpCidrsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setIpCidrsList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addIpCidrs = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearIpCidrsList = function() {
  return this.setIpCidrsList([]);
};


/**
 * repeated string source_ip_cidrs = 14;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getSourceIpCidrsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setSourceIpCidrsList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addSourceIpCidrs = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearSourceIpCidrsList = function() {
  return this.setSourceIpCidrsList([]);
};


/**
 * repeated string domains = 15;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getDomainsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setDomainsList = function(value) {
  return jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addDomains = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearDomainsList = function() {
  return this.setDomainsList([]);
};


/**
 * repeated string domain_suffixes = 16;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getDomainSuffixesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 16));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setDomainSuffixesList = function(value) {
  return jspb.Message.setField(this, 16, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addDomainSuffixes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 16, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearDomainSuffixesList = function() {
  return this.setDomainSuffixesList([]);
};


/**
 * repeated string domain_keywords = 17;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getDomainKeywordsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 17));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setDomainKeywordsList = function(value) {
  return jspb.Message.setField(this, 17, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addDomainKeywords = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 17, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearDomainKeywordsList = function() {
  return this.setDomainKeywordsList([]);
};


/**
 * repeated string domain_regexes = 18;
 * @return {!Array<string>}
 */
proto.config.Rule.prototype.getDomainRegexesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 18));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.setDomainRegexesList = function(value) {
  return jspb.Message.setField(this, 18, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.addDomainRegexes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 18, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.config.Rule} returns this
 */
proto.config.Rule.prototype.clearDomainRegexesList = function() {
  return this.setDomainRegexesList([]);
};


/**
 * @enum {number}
 */
proto.config.Outbound = {
  PROXY: 0,
  DIRECT: 1,
  DIRECT_WITH_FRAGMENT: 2,
  BLOCK: 3
};

/**
 * @enum {number}
 */
proto.config.Network = {
  ALL: 0,
  TCP: 1,
  UDP: 2
};

/**
 * @enum {number}
 */
proto.config.Protocol = {
  TLS: 0,
  HTTP: 1,
  QUIC: 2,
  STUN: 3,
  DNS: 4,
  BITTORRENT: 5
};

goog.object.extend(exports, proto.config);
