// source: v2/hcore/tunnelservice/tunnel.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.tunnelservice.TunnelResponse', null, global);
goog.exportSymbol('proto.tunnelservice.TunnelStartRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tunnelservice.TunnelStartRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tunnelservice.TunnelStartRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tunnelservice.TunnelStartRequest.displayName = 'proto.tunnelservice.TunnelStartRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tunnelservice.TunnelResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tunnelservice.TunnelResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tunnelservice.TunnelResponse.displayName = 'proto.tunnelservice.TunnelResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tunnelservice.TunnelStartRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.tunnelservice.TunnelStartRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tunnelservice.TunnelStartRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tunnelservice.TunnelStartRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ipv6: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    serverPort: jspb.Message.getFieldWithDefault(msg, 2, 0),
    serverUsername: jspb.Message.getFieldWithDefault(msg, 3, ""),
    serverPassword: jspb.Message.getFieldWithDefault(msg, 4, ""),
    strictRoute: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    endpointIndependentNat: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    stack: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tunnelservice.TunnelStartRequest}
 */
proto.tunnelservice.TunnelStartRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tunnelservice.TunnelStartRequest;
  return proto.tunnelservice.TunnelStartRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tunnelservice.TunnelStartRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tunnelservice.TunnelStartRequest}
 */
proto.tunnelservice.TunnelStartRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIpv6(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setServerPort(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerUsername(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerPassword(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStrictRoute(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEndpointIndependentNat(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setStack(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tunnelservice.TunnelStartRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tunnelservice.TunnelStartRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tunnelservice.TunnelStartRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tunnelservice.TunnelStartRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIpv6();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getServerPort();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getServerUsername();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getServerPassword();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStrictRoute();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getEndpointIndependentNat();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getStack();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional bool ipv6 = 1;
 * @return {boolean}
 */
proto.tunnelservice.TunnelStartRequest.prototype.getIpv6 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tunnelservice.TunnelStartRequest} returns this
 */
proto.tunnelservice.TunnelStartRequest.prototype.setIpv6 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional int32 server_port = 2;
 * @return {number}
 */
proto.tunnelservice.TunnelStartRequest.prototype.getServerPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tunnelservice.TunnelStartRequest} returns this
 */
proto.tunnelservice.TunnelStartRequest.prototype.setServerPort = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string server_username = 3;
 * @return {string}
 */
proto.tunnelservice.TunnelStartRequest.prototype.getServerUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnelservice.TunnelStartRequest} returns this
 */
proto.tunnelservice.TunnelStartRequest.prototype.setServerUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string server_password = 4;
 * @return {string}
 */
proto.tunnelservice.TunnelStartRequest.prototype.getServerPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnelservice.TunnelStartRequest} returns this
 */
proto.tunnelservice.TunnelStartRequest.prototype.setServerPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool strict_route = 5;
 * @return {boolean}
 */
proto.tunnelservice.TunnelStartRequest.prototype.getStrictRoute = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tunnelservice.TunnelStartRequest} returns this
 */
proto.tunnelservice.TunnelStartRequest.prototype.setStrictRoute = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool endpoint_independent_nat = 6;
 * @return {boolean}
 */
proto.tunnelservice.TunnelStartRequest.prototype.getEndpointIndependentNat = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tunnelservice.TunnelStartRequest} returns this
 */
proto.tunnelservice.TunnelStartRequest.prototype.setEndpointIndependentNat = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string stack = 7;
 * @return {string}
 */
proto.tunnelservice.TunnelStartRequest.prototype.getStack = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnelservice.TunnelStartRequest} returns this
 */
proto.tunnelservice.TunnelStartRequest.prototype.setStack = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tunnelservice.TunnelResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.tunnelservice.TunnelResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tunnelservice.TunnelResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tunnelservice.TunnelResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tunnelservice.TunnelResponse}
 */
proto.tunnelservice.TunnelResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tunnelservice.TunnelResponse;
  return proto.tunnelservice.TunnelResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tunnelservice.TunnelResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tunnelservice.TunnelResponse}
 */
proto.tunnelservice.TunnelResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tunnelservice.TunnelResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tunnelservice.TunnelResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tunnelservice.TunnelResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tunnelservice.TunnelResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.tunnelservice.TunnelResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnelservice.TunnelResponse} returns this
 */
proto.tunnelservice.TunnelResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.tunnelservice);
